#!/usr/bin/env bash
# ============================================================
# traffic-ai — Remove Unused Files & Folders
# ============================================================
# Run from the ROOT of the project:
#   cd traffic-ai
#   bash cleanup_unused.sh
#
# What this removes (and WHY):
#
# 1. backend/app/traffic_logic.py
#    Duplicate of services/traffic_logic.py. The routes import from
#    app.services.traffic_logic — this root-level copy is never imported.
#
# 2. backend/app/services/simulation_service.py
#    A standalone timing-calculation module. Nothing in routes/,
#    services/, or main.py imports it.
#
# 3. backend/app/services/yolo_service.py
#    A second YOLO detection implementation. The actual route
#    (routes/analyze.py) imports app.services.ai_detector, not this file.
#
# 4. frontend/app/components/VehicleSimulation.tsx
#    Exported but never imported by any page or component.
#
# 5. frontend/app/components/TrafficLights.tsx
#    Exported but never imported by any page or component.
#
# 6. frontend/.next/
#    Build-time cache generated by Next.js. Excluded from .gitignore
#    but should NOT be committed. Regenerated by `npm run dev / build`.
#
# 7. backend/yolov8n.pt
#    6.5 MB binary weight file committed directly to the repo.
#    The model/ README explicitly says weights are auto-downloaded and
#    should NOT be committed. The .gitignore covers model/*.pt but
#    not this copy.
#
# 8. model/ directory
#    Contains only a README note saying weights live here.
#    The actual weights are auto-downloaded by ultralytics into the
#    backend working directory — this folder adds no runtime value.
#
# 9. pygame_sim.py (root level)
#    A standalone Pygame desktop simulator. It is not imported by the
#    FastAPI backend or the Next.js frontend. It is an independent
#    script that duplicates simulation logic already handled by the
#    web stack. Removing it has zero impact on the running app.
# ============================================================

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo ""
echo "=== traffic-ai Cleanup Script ==="
echo "Project root: $PROJECT_ROOT"
echo ""

remove() {
  local path="$PROJECT_ROOT/$1"
  if [ -e "$path" ] || [ -L "$path" ]; then
    rm -rf "$path"
    echo "  [REMOVED] $1"
  else
    echo "  [SKIP]    $1  (already gone)"
  fi
}

echo "── Backend: duplicate / unreferenced files ──────────────────────"
remove "backend/app/traffic_logic.py"          # duplicate of services/traffic_logic.py
remove "backend/app/services/simulation_service.py"  # never imported
remove "backend/app/services/yolo_service.py"         # never imported (ai_detector.py is used)

echo ""
echo "── Frontend: unused React components ───────────────────────────"
remove "frontend/app/components/VehicleSimulation.tsx"  # never imported by any page
remove "frontend/app/components/TrafficLights.tsx"      # never imported by any page

echo ""
echo "── Build artefacts that should not be committed ────────────────"
remove "frontend/.next"                         # Next.js build cache

echo ""
echo "── Binary model weights committed by mistake ───────────────────"
remove "backend/yolov8n.pt"                    # 6.5 MB; auto-downloaded by ultralytics

echo ""
echo "── Empty / documentation-only directories ──────────────────────"
remove "model"                                  # only contains a README, no runtime purpose

echo ""
echo "── Root-level standalone script (not part of web stack) ────────"
remove "pygame_sim.py"                          # independent Pygame desktop app

echo ""
echo "=== Done. All unused files removed. ==="
echo ""
echo "Next steps:"
echo "  • cd frontend && npm install && npm run dev"
echo "  • cd backend  && pip install -r requirements.txt && uvicorn app.main:app --reload"
echo "  • The YOLO weights will be auto-downloaded on the first /analyze-image request."
echo ""
