import os

content = (
    "from dataclasses import dataclass, field\n"
    "from typing import Optional\n\n"
    "@dataclass\n"
    "class SubLaneCounts:\n"
    "    straight: int = -1\n"
    "    left: int = -1\n"
    "    right: int = -1\n"
    "    def is_specified(self):\n"
    "        return self.straight >= 0 or self.left >= 0 or self.right >= 0\n"
    "    def to_dict(self):\n"
    "        if not self.is_specified(): return {}\n"
    "        return {'straight': max(0,self.straight), 'left': max(0,self.left), 'right': max(0,self.right), 'total': max(0,self.straight)+max(0,self.left)+max(0,self.right)}\n\n"
    "@dataclass\n"
    "class LaneState:\n"
    "    vehicle_count: int = 0\n"
    "    queue_length: int = 0\n"
    "    avg_wait_time: float = 0.0\n"
    "    sub_lanes: SubLaneCounts = field(default_factory=SubLaneCounts)\n\n"
    "class TrafficLogic:\n"
    "    MIN_GREEN = 10\n"
    "    MAX_GREEN = 60\n"
    "    SEC_PER_VEHICLE = 3\n"
    "    BASE_GREEN = 8.0\n"
    "    QUEUE_WEIGHT = 2.5\n"
    "    WAIT_WEIGHT = 0.4\n"
    "    DIRECTIONS = ['north', 'south', 'east', 'west']\n"
    "    @staticmethod\n"
    "    def _extract_int(value):\n"
    "        if isinstance(value, int): return value\n"
    "        if isinstance(value, dict): return int(sum(value.values()))\n"
    "        total = 0\n"
    "        for attr in ('cars','bikes','trucks','buses','rickshaws'): total += int(getattr(value,attr,0) or 0)\n"
    "        return total\n"
    "    def _clamp(self, t): return max(self.MIN_GREEN, min(self.MAX_GREEN, int(round(t))))\n"
    "    def calculate_cycle(self, densities):\n"
    "        raw = {d: densities.get(d,0) for d in self.DIRECTIONS} if hasattr(densities,'__getitem__') else {d: getattr(densities,d,0) for d in self.DIRECTIONS}\n"
    "        counts = {d: max(0,self._extract_int(raw[d])) for d in self.DIRECTIONS}\n"
    "        total = sum(counts.values())\n"
    "        results = []\n"
    "        for d in self.DIRECTIONS:\n"
    "            results.append({'lane':d,'green_time':self.MIN_GREEN if total==0 else self._clamp(counts[d]*self.SEC_PER_VEHICLE),'vehicle_count':counts[d],'queue_length':counts[d],'avg_wait_time':0.0,'sub_lanes':{},'mode':'legacy'})\n"
    "        results.sort(key=lambda x:(x['vehicle_count'],x['green_time']),reverse=True)\n"
    "        return results\n"
    "    def calculate_adaptive_cycle(self, lane_states, queue_weight=None, wait_weight=None):\n"
    "        qw = queue_weight if queue_weight is not None else self.QUEUE_WEIGHT\n"
    "        ww = wait_weight if wait_weight is not None else self.WAIT_WEIGHT\n"
    "        results = []\n"
    "        for d in self.DIRECTIONS:\n"
    "            state = lane_states.get(d, LaneState())\n"
    "            vc,ql,wt = max(0,int(state.vehicle_count)),max(0,int(state.queue_length)),max(0.0,float(state.avg_wait_time))\n"
    "            raw_score = self.BASE_GREEN+(ql*qw)+(wt*ww)\n"
    "            results.append({'lane':d,'green_time':self._clamp(raw_score),'vehicle_count':vc,'queue_length':ql,'avg_wait_time':round(wt,1),'raw_score':round(raw_score,2),'sub_lanes':state.sub_lanes.to_dict(),'mode':'adaptive'})\n"
    "        results.sort(key=lambda x:x['raw_score'],reverse=True)\n"
    "        return results\n"
    "    def calculate_emergency_cycle(self, priority_lane):\n"
    "        if priority_lane not in self.DIRECTIONS: raise ValueError('Invalid lane')\n"
    "        results = [{'lane':d,'green_time':self.MAX_GREEN if d==priority_lane else self.MIN_GREEN,'vehicle_count':0,'queue_length':0,'avg_wait_time':0.0,'raw_score':float(self.MAX_GREEN if d==priority_lane else self.MIN_GREEN),'sub_lanes':{},'mode':'emergency'} for d in self.DIRECTIONS]\n"
    "        results.sort(key=lambda x:x['green_time'],reverse=True)\n"
    "        return results\n\n"
    "traffic_logic = TrafficLogic()\n"
)

path = os.path.join("app", "services", "traffic_logic.py")
with open(path, "w") as f:
    f.write(content)
print("Done —", path, "written")